name: Zbarrier
version: ${version}
main: ru.zoobastiks.zbarrier.ZbarrierPlugin
api-version: '1.21'
authors: [Zoobastiks]
website: https://t.me/Zoobastiks
commands:
  zbarrier:
    description: Manage world barriers
    usage: /zbarrier help
    aliases: [zb]
permissions:
  zbarrier.admin:
    description: Full access to Zbarrier commands
    default: op
  zbarrier.reload:
    description: Reload Zbarrier configuration
    default: op
